apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: {{ .Values.dbnamespace}}
  labels:
    {{- toYaml .Values.labels | nindent 4}}
spec:
  selector: 
    {{- toYaml .Values.dblabels | nindent 4}}
  clusterIP: None
  ports:
    - port: 3306
