apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-container
  namespace: {{ .Values.dbnamespace}}
  labels:
    {{- toYaml .Values.labels | nindent 4}}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 8}}
    spec:
      containers:
        - name: {{ .Values.dbcontainers.name}}
          image: {{ .Values.dbcontainers.image}}
          ports:
            - containerPort: {{ .Values.dbcontainers.port}}
              name: mysql-container
          env:
            - name: MYSQL_ROOT_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretname}}
                  key: rootpassword
          volumeMounts:
            - name: db-pvc
              mountPath: /var/lib/mysql
      volumes:
        - name: db-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.pvcname}}

