apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: {{ .Values.gonamespace}}
  labels:
    {{- toYaml .Values.golabels | nindent 4}}
spec:
  selector: 
    {{- toYaml .Values.golabels | nindent 4}}
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer