apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretname}}
  namespace: {{ .Values.gonamespace}}
  labels:
    {{- toYaml .Values.labels | indent 4}}
type: Opaque
data:
  rootpassword: {{ .Values.data.password}}