apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: {{ .Values.dbnamespace}}
  labels:
    {{- toYaml .Values.labels | nindent 4}}
spec:
  storageClassName: {{ .Values.storageclassname}}
  capacity:
    storage: {{ .Values.capacity}}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.accessMode}}
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "home/new4"