apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-storage
  namespace: {{ .Values.dbnamespace}}
  labels:
    {{- toYaml .Values.labels | nindent 4}}
parameters:
  type: {{ .Values.parameters.type}}
reclaimPolicy: Retain
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate