name: Fyfirstjob
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: print the path
        run: pwd
      - name: print the vm name
        run: whoami
  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: print the given element
        run: echo "this is the second job"
      - name: print the any element
        run: echo "this is the third job"