name: Golang CICD

on: workflow_dispatch

jobs:
  Golang_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build this golang
        uses: ./.github/actions/build
  
  SonarQube:
    runs-on: ubuntu-22.04
    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}